EdgeApp/edge-currency-bitcoin

.flowconfig, package.json, rollup.config.js, rollup.config.test.js, src/currencyEngine/index.js, test/bitcoin/3-bip44/engine.js, test/bitcoin/4-bip32-Lagacy/engine.js, test/litecoin/2-bip44/engine.js
Change getFreshAddress to return an AbcFreshAddress object vs a single address string
Flow all touched files
=> Change get fresh address

.eslintrc.json, package-lock.json, package.json, readme.md, rollup.config.js, rollup.config.test.js, src/jsonSchemas.js, src/miningFees.js, src/serverCache.js, test/miningFeesTest.js, test/serverCacheTest.js
This enables better Flow, Prettier, ESlint (standard config), better pre-commit hooks, and such.
=> Build system

src/plugin/currencyPlugin.js, test/plugin/fixtures.json
Added the option to pass in "legacyAddress" to encodeUri as part of the AbcEncodeUri.
=> LegacyAddress support in encodeUri

src/engine/currencyEngine.js, src/engine/engineState.js
This is a super super precise implementation for "onAddressesChecked" as a preparation for "sweeping keys" which will require the wallet to be fully sync to avoid multiple transactions.
=> onAddressesChecked

src/engine/currencyEngine.js, src/engine/keyManager.js, test/KeyManager.js
Move the seed getters into the keyManager
=> Refactor to code 

package.json, src/info/zcoin.js, src/plugin/currencyPlugin.js, test/plugin/fixtures.json, test/plugin/plugin.js, yarn.lock
This is a BREAKING change so be careful before using it.
Task link: https://app.asana.com/0/361770107085503/616058479826340/f
Read all the commit comments for more information.
=> Allow for Parse Uri to recognize legacy address

src/engine/engineState.js
Since we only need 3 servers but we ask for 8, have refillServers go through all 8 before it calls getServers again. This ensures that all 8 servers have a chance to be scored before pinging the cache again. Othewise, we could end up with some unused servers in the list that never get tried.
Implemented by simply holding the serverList in the engineState object instead of a local variable in refillServers.
Note that this exact logic was how Airbitz used the serverCache
=> Change refillServers to deplete serverList before calling getServers

src/info/dash.js, src/info/feathercoin.js, src/info/litecoin.js, src/info/zcoin.js, test/plugin/fixtures.json
Fix sweepKey for the following coins: Dash, Litecoin, Feathercoin and Zcoin.
Needed to change the privKeys prefixes
=> Fix sweepKey

CHANGELOG.md, package.json, src/engine/currencyEngine.js
Set the 'Accept' Header to be the correct type for a bip70 payment request.
=> Bip70 headers

src/engine/currencyEngine.js, src/engine/engineState.js, src/engine/keyManager.js, src/engine/paymentRequest.js, src/plugin/currencyPlugin.js, src/plugin/pluginState.js, src/plugin/uri.js, src/utils/addressFormat/bn.js, src/utils/addressFormat/cashAddress.js, src/utils/bcoinExtender/replayProtection.js, src/utils/coinUtils.js, src/utils/formatSelector.js, test/engine/currencyEngine/currencyEngine.js, test/engine/paymentRequest.js
1. Removed Almost all of the $FlowFixMe
2. Prettify (npm run format)
=> $FlowFixMe Cleanup

src/engine/currencyEngine.js, src/info/bitcoin.js, src/info/bitcoincash.js, src/info/bitcoincashtestnet.js, src/info/bitcoingold.js, src/info/bitcoingoldtestnet.js, src/info/bitcointestnet.js, src/info/constants.js, src/info/dash.js, src/info/litecoin.js, src/info/qtum.js, src/info/ufo.js, src/plugin/currencyPlugin.js, src/plugin/pluginState.js, test/engine/currencyEngine/fixtures.json
Make all coins try and query the infoServer
=> Get fee for all coins

src/engine/keyManager.js, src/info/digibyte.js, src/utils/coinUtils.js, src/utils/formatSelector.js
Fixes for:
https://app.asana.com/0/361770107085503/777433575085515/f
https://app.asana.com/0/361770107085503/777433575085498/f
https://app.asana.com/0/361770107085503/777433575085499/f
=> Sweep key fixes

.flowconfig, mocha-config.json, package.json, src/engine/currencyEngine.js, src/engine/paymentRequest.js, yarn.lock
Add support for the proprietary "Bip70" version that Bitpay are using
=> Bitpay Payment

src/index.js, src/info/eboost.js
Adds EBoost Support.
Not yet ready for merge. 
The 3 servers listed aren't yet running. but should be within the next day. WIll update once done
=> [Networks] Add EBoost Support

src/engine/keyManager.js, src/info/bitcoincash.js, src/info/bitcoincashtestnet.js, src/info/bitcoingold.js, src/info/bitcoingoldtestnet.js, src/info/bitcointestnet.js, src/info/digibyte.js, src/plugin/uri.js
- Remove any reference to `currencyName` inside the code (use `pluginName` instead since it's unique and immutable)
- Update some currencies' names
=> Currency Name changes

src/engine/currencyEngine.js, src/info/bitcoin.js, src/info/bitcoincash.js, src/info/bitcoingold.js, src/info/dash.js, src/info/digibyte.js, src/info/dogecoin.js, src/info/feathercoin.js, src/info/litecoin.js, src/info/qtum.js, src/info/ufo.js, src/info/vertcoin.js, src/info/zcoin.js, src/plugin/currencyPlugin.js, src/plugin/pluginState.js, test/engine/currencyEngine/currencyEngine.js
Full implementation of `plugin.changeSettings`
=> changeSettings

src/info/constants.js, src/plugin/pluginState.js
Disable Digibyte sending on previous broken versions
=> Change the server path for Digibyte

src/engine/currencyEngine.js
* Hold bcoinTx object in the plugin and return a handle to the plugin instead
=> Sanitize edgeTransaction returned from makeSpend

src/plugin/uri.js
https://app.asana.com/0/361770107085503/958253396923268/f
=> Handle category and notes metadata correctly when parsing URIs

src/engine/currencyEngine.js
Asana Task: https://app.asana.com/0/361770107085503/1114190398895351/f
=> Return dropped tx block height as -1

src/engine/currencyEngine.js, src/engine/miningFees.js, src/info/bitcointestnet.js, test/engine/miningFees/miningFees.js
Prevent fee object from getting mutated and fix max vs minFee rassignment
Asana Task https://app.asana.com/0/361770107085503/1117758945319402/f
=> Fix Fee Issues

src/plugin/serverCache.js
Verbally approved by Paul and Eli
=> Fix LTC electrum server algo issue

src/info/vertcoin.js
Previous explorer couldn't find unused addresses
=> Updated explorer to vertcoin.org

src/engine/currencyEngine.js, src/info/bitcoin.js
=> Change 21.com to bitcoinfees.earn.com for mining Fees

src/plugin/serverCache.js
Modify score of re-added servers to -10 to help prioritize them over dropped servers.
=> Adjust Electrum scoring

src/engine/miningFees.js, test/engine/miningFees/earnComTestFees.json
Asana Task: https://app.asana.com/0/361770107085503/1124807987833505/f
=> Fix Earn.com fees data structure issue

src/info/all.js, src/info/badcoin.js
Adds badcoin support, logo's are incorrect however. ( currently eboost ) lmk if you need BAD logo
=> Integrate badcoin

src/utils/coinUtils.js
Here's a demo: https://anypayinc.s3.amazonaws.com/videos/telegram-cloud-document-1-5006059471848341683.mp4
=> Allow pay:// URL Protocol Prefix For All Bitcoins

src/engine/engineState.js, src/stratum/stratumConnection.js, test/stratum/stratumConnection.js
Replace error message and downgrade bad server
=> Hack to identify spam electrum server responses

.flowconfig, package.json, webpack.config.js, yarn.lock
Webpack 4 has some vulnerable dependencies, so we need to get off that.
=> Upgrade to webpack 5

src/plugin/uri.js, test/plugin/currencyPlugin/fixtures.json
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1201617140921562
=> Add support for RenBridge Gateway address uri

src/utils/formatSelector.js
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202163449679166
=> Fix 1sat/byte fee corner case when segwit tx has 1 input and 1 output
