EdgeApp/edge-currency-bitcoin

src/engine/engineState.js

Some electrum servers do return unconfirmed UTXO's so filter those from the pendingTxids list
Asana task: https://app.asana.com/0/361770107085503/565600412505649/f

BCH double balance fix

---

src/engine/engineState.js
src/plugin/pluginState.js
src/plugin/serverCache.js

This PR changes the frequency of the when we save the cache to disk.
Instead of saving only after a certain time has passed, save if one of this 2 happens:
1. The engine is fully synced.
2. If the synced status has changed by more then 10%.
And in both cases a save will occur only if we have received new data from the servers and/or the server score changed.
It fixes the bug in this task: https://app.asana.com/0/361770107085503/589896675713943/f

Improve caching

---

CHANGELOG.md
src/engine/currencyEngine.js

Check for 0 value or null address output and skip output if so

Prevent throw when wallet has an OP_RETURN transaction output

---

CHANGELOG.md
package.json
src/engine/engineState.js
src/info/zcoin.js
src/plugin/serverCache.js

- Set the response time if serverScoreDown() is called. This prevents this server from being considered "new" and being tried again in the future at the top of the list.
- Fix port numbers for zcoin electrum servers
- Fix zcoin block explorer urls
- Completely ignore electrums: urls for now

Small connectivity fixes

---

src/engine/currencyEngine.js

An invalid URL crashes the app because an exception is not handled
on a much lower level. An URL can be invalid if for example
`infoServer` has not been set.
Relevant stacktrace:
> E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
E AndroidRuntime: Process: co.edgesecure.app, PID: 23930
E AndroidRuntime: java.lang.IllegalArgumentException: unexpected url: /networkFees/FTC
E AndroidRuntime:     at okhttp3.Request$Builder.url(Request.java:142)

currencyEngine: fix Android crash

---

src/engine/engineState.js

Unconfirmed transactions have a height of -1 and querying for headers from block -1 causes failures on all servers that we access and causes infinite disconnect/reconnect.

Do not try to fetch headers for heights < 0

---

src/engine/currencyEngine.js

Fixes the issue where trying to sweep from a key that has a higher balance then our own wallet, gets an incorrect InsufficientFundsError error.

Fix for unnecessary `InsufficientFundsError`

---

src/info/feathercoin.js

All Feathercoin ElectrumX servers now run Feathercoin 0.16 (based on Bitcoin Core 0.16) and therefore support SegWit now.
Have a nice week!

Feathercoin: Activate SegWit

---

src/engine/currencyEngine.js
src/engine/keyManager.js
src/plugin/currencyPlugin.js
src/utils/coinUtils.js
src/utils/formatSelector.js

Moved the following functions:
1. sign
2. getMasterKeys
3. keyFromSecret
4. deriveHdKey
5. seedFromEntropy
6. getLock
7. getXPubFromSeed
Another step in goal to abstract bcoin from the rest of the code

Move more functions into `formatSelector/coinUtils`

---

src/engine/currencyEngine.js

Set the timestamp after we requested fees from the server no matter the outcome of the result.
It fixes this bug:
https://app.asana.com/0/361770107085503/714313720551065/f

Throttle the calls to update the fee correctly

---

src/engine/currencyEngine.js
src/engine/keyManager.js
src/utils/coinUtils.js

This PR fixes the problem when trying to send money to a network that has both Segwit and a legacy address format (like Litecoin or UFO).

Legacy format issues

---

src/index.js
src/info/eboost.js
src/utils/addressFormat/addressFormatIndex.js
test/utils/addressFormat/addressFormatIndex/fixtures.json

Add EBoost Support and fix some buggy edge cases that happened since EBoost's new format overlaps with another network's prefix.
No need to review the file `src/info/eboost.js` or the tests.

Add EBoost Support

---

src/utils/coinUtils.js

Digibyte uses the same address prefix as something called 'simnet', so bcoin choses the wrong network and writes the wrong script, which burns the change.

Fix Digibyte change address problem

---

src/engine/currencyEngine.js

A fix to solve asana task "Custom Nodes - Still able to send and detect transactions even if turned on with an invalid server"

skip sending tx on brodcasters when user added a custom node

---

src/engine/currencyEngine.js
src/engine/engineState.js
test/engine/currencyEngine/currencyEngine.js
test/stratum/stratumConnection.js

This needs to coincide with PR https://github.com/EdgeApp/edge-core-js/pull/152
This optimizes login to not need to load transactions off disk until they are requested by user.

Myriad of transaction loading optimizations

---

src/engine/currencyEngine.js

If BitPay sends a floating-point fee, we would round it down to the nearest integer and therefore send too little. This calculation keeps the fee in float until the end, and then rounds up.

Fix BitPay fee calculation

---

src/engine/currencyEngine.js
src/engine/engineState.js
src/plugin/serverCache.js
src/utils/coinUtils.js
src/utils/formatSelector.js

* Only show first 6 chars of wallet ID
* Paraphrase some logging descriptions
* Remove "electrum://" from url logging
This helps when trying to sequence of what happened during network issues

Shrink the line width of logging spew

---

src/engine/currencyEngine.js
src/utils/coinUtils.js

Remove the `pendingSpends` state in favor of a much better stateless solution.

Sanitize edge transaction

---

.travis.yml
Jenkinsfile
test/plugin/serverCache.js
yarn.lock

These tests are sensitive to the node.js version being used, since the scores are the same in several cases, making the sort order implementation-dependent.
This locks us to a recent node.js version, and updates the tests to match that.

Fix the server score tests

---

src/plugin/currencyPlugin.js
test/engine/currencyEngine/currencyEngine.js
test/plugin/currencyPlugin/currencyPlugin.js

This will fix both the performance problem and the `InvalidWalletType` errors.

Disable `derivePublicKey` for now

---

src/info/litecoin.js

Previous explorer wasn't compatible with m-address

Update LTC to blockchair

---

src/engine/keyManager.js
src/utils/coinUtils.js

All BCH wallets would crash on first login, but there was bogus catch statement hiding the error. Removing the catch statement exposes the error, which is passing hex data into a method that expects script (like "OP_X OP_Y"). Changing the method fixes the issue.

Fix BCH -> BSV splitting

---

src/utils/logger.js

The purpose of this task is to change the plugin errors to warning-level so that they don't create a red screen of death in the GUI

Change logger error to warn to prevent red screen of death in GUI

---

src/engine/engineState.js

This keeps the "lastScoreUpTime_" refreshed so the serverCache doesn't think we are offline

Add server score up to subscribe hash

---

src/engine/engineState.js
src/plugin/serverCache.js

Limit reconnectCounter at 5 sec to reduce connection issues
Make lastScoreUpTime_ global

Max reconnect counter at 5 sec and make lastScoreUpTime_ global

---

src/engine/broadcastApi.js
src/engine/currencyEngine.js
src/engine/keyManager.js

Include bcoin's data regarding inputs, outputs, size, and witness size
into EdgeTransaction's otherparams.debugInfo for debugging purposes
WIP inputs and outputs
Change otherParams inputs and outputs to general debugInfo string

Include debugInfo in transaction otherParams field

---

src/engine/currencyEngine.js
src/engine/keyManager.js
src/info/bitcoin.js
src/info/bitcoincash.js
src/info/bitcoincashtestnet.js
src/info/bitcoingold.js
src/info/bitcoingoldtestnet.js
src/info/bitcoinsv.js
src/info/bitcointestnet.js
src/info/dash.js
src/info/digibyte.js
src/info/dogecoin.js
src/info/eboost.js
src/info/feathercoin.js
src/info/groestlcoin.js
src/info/litecoin.js
src/info/qtum.js
src/info/ravencoin.js
src/info/smartcash.js
src/info/ufo.js
src/info/vertcoin.js
src/info/zcoin.js
src/utils/coinUtils.js

Hitting the `maxFee` looks like an `InsufficientFundsError`, which is wrong. The GUI has its own fiat-based fee warnings, so we don't need this.

Don't send a `maxFee` to the bcoin picker

---

src/info/dogecoin.js

Dogecoin has [merged mining](https://en.bitcoin.it/wiki/Merged_mining_specification), which means the headers can be other sizes than 80 bytes.

Allow merge-mined Dogecoin blocks

---

src/utils/coinUtils.js

These checks don't make sense for other coins, and are actually making big wallets (with > 21 million coins) un-spendable.

Remove the bitcoin-centric sanity checks

---

src/engine/currencyEngine.js

Currently errors in the `CurrencyEngine.makeSpend` are not consistent. It's very difficult to properly handle InsufficientFundsError as it's thrown as a plain JS Error under circumstances when `FundingError` occurs.
This MR fixes incorrect error type in `makeSpend` method.

Fix InsufficientFundsError type in makeSpend method

---

src/engine/paymentRequest.js

Enables Anypay servers to know for which coin to provide a payment request, since Anypay handles all coins at a single URL.
Customers can pay with BTC, BCH, or BSV without needing to tell the cashier which are going to use.
Here you may watch of me demonstrating with explanation the user experience benefits of the this pull request:
https://anypayinc.s3.amazonaws.com/videos/telegram-cloud-document-1-5012867969970077867.mp4

Specify Header X-Currency To Indicate Coin In JSON V2 Pay Protocol

---

src/engine/currencyEngine.js
src/info/dogecoin.js
src/utils/coinUtils.js
yarn.lock

Update to newer version of bcoin that removes MAX_FEE on rate and hardFee. This limit was no longer necessary since GUI shows fee warning modal for high fee.

Add hardFee to fix Dogecoin fees to 1 DOGE

---

src/info/badcoin.js
src/info/constants.js
src/info/eboost.js

Now that the info server uses Caddy, we can drop the weird port.
Also, it turns out that the engine info no longer has an `infoServer` property since https://github.com/EdgeApp/edge-currency-bitcoin/commit/4064fac53293c99d08438c4502f70bd992bb3f81, so we can just drop those.

Upgrade to the new info server URL

---

src/utils/bcoinExtender/patchCrypto.js

Since the react-native-fast-crypto library isn't always working on older Androids, we can just fall back on JS if something goes wrong.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202119846830150

Work around Android PBKDF2 failures
